import { NFTCardType } from '@/types'

export const dummyNFTs = [
  {
    id: '1',
    name: 'CryptoPunk #1',
    image: 'https://picsum.photos/200',
    description: 'A rare CryptoPunk with unique traits.',
    collectionName: 'CryptoPunks',
    tokenId: '1',
    contractAddress: '0x123456789abcdef123456789abcdef123456789a',
    tokenStandard: 'ERC-721',
    blockchain: 'Ethereum',
    owner: '0xabcdef123456789abcdef123456789abcdef1234',
    creator: 'Larva Labs',
    attributes: [
      { trait_type: 'Type', value: 'Male' },
      { trait_type: 'Accessory', value: 'Mohawk' },
      { trait_type: 'Background', value: 'Blue' },
    ],
    lastSalePrice: '100 ETH',
    lastSaleDate: '2023-05-01T12:00:00Z',
  },
  {
    id: '2',
    name: 'Bored Ape #42',
    image: 'https://picsum.photos/200',
    description: 'A bored ape with a funky hat and sunglasses.',
    collectionName: 'Bored Ape Yacht Club',
    tokenId: '42',
    contractAddress: '0x987654321fedcba987654321fedcba987654321f',
    tokenStandard: 'ERC-721',
    blockchain: 'Ethereum',
    owner: '0xfedcba987654321fedcba987654321fedcba9876',
    creator: 'Yuga Labs',
    attributes: [
      { trait_type: 'Background', value: 'Yellow' },
      { trait_type: 'Fur', value: 'Brown' },
      { trait_type: 'Clothes', value: 'Striped Tee' },
      { trait_type: 'Mouth', value: 'Bored' },
      { trait_type: 'Eyes', value: 'Sunglasses' },
    ],
    lastSalePrice: '80 ETH',
    lastSaleDate: '2023-04-15T14:30:00Z',
  },
  {
    id: '3',
    name: 'Art Blocks #78',
    image: 'https://picsum.photos/200',
    description: 'A generative art piece from the Art Blocks collection.',
    collectionName: 'Art Blocks Curated',
    tokenId: '78',
    contractAddress: '0xabcdef123456789abcdef123456789abcdef1234',
    tokenStandard: 'ERC-721',
    blockchain: 'Ethereum',
    owner: '0x123456789abcdef123456789abcdef123456789a',
    creator: 'Tyler Hobbs',
    attributes: [
      { trait_type: 'Series', value: 'Fidenza' },
      { trait_type: 'Color Palette', value: 'Vibrant' },
      { trait_type: 'Complexity', value: 'High' },
    ],
    lastSalePrice: '50 ETH',
    lastSaleDate: '2023-03-20T09:45:00Z',
  },
  {
    id: '4',
    name: 'Cool Cat #99',
    image: 'https://picsum.photos/200',
    description: 'A cool cat with a stylish outfit.',
    collectionName: 'Cool Cats NFT',
    tokenId: '99',
    contractAddress: '0xfedcba987654321fedcba987654321fedcba9876',
    tokenStandard: 'ERC-721',
    blockchain: 'Ethereum',
    owner: '0x987654321fedcba987654321fedcba987654321f',
    creator: 'Cool Cats Team',
    attributes: [
      { trait_type: 'Body', value: 'Blue' },
      { trait_type: 'Hat', value: 'Beanie' },
      { trait_type: 'Face', value: 'Happy' },
      { trait_type: 'Outfit', value: 'Hoodie' },
    ],
    lastSalePrice: '5 ETH',
    lastSaleDate: '2023-05-10T16:20:00Z',
  },
  {
    id: '5',
    name: 'Meebit #123',
    image: 'https://picsum.photos/200',
    description: 'A voxel-based 3D character from the Meebits collection.',
    collectionName: 'Meebits',
    tokenId: '123',
    contractAddress: '0x123abcdef456789abcdef123456789abcdef1234',
    tokenStandard: 'ERC-721',
    blockchain: 'Ethereum',
    owner: '0xabcdef987654321abcdef987654321abcdef9876',
    creator: 'Larva Labs',
    attributes: [
      { trait_type: 'Type', value: 'Human' },
      { trait_type: 'Outfit', value: 'Spacesuit' },
      { trait_type: 'Background', value: 'Gradient' },
      { trait_type: 'Pose', value: 'Standing' },
    ],
    lastSalePrice: '3.5 ETH',
    lastSaleDate: '2023-04-30T11:15:00Z',
  },
]

export function dummyNFTCards(): NFTCardType[] {
  return dummyNFTs.map((nft) => ({
    id: nft.id,
    name: nft.name,
    symbol: '',
    decimals: '',
    balance: '1',
    contractAddress: nft.contractAddress,
    tokenId: parseInt(nft.tokenId),
    tokenURI: nft.image,
    type: 'ERC-721',
    image: nft.image,
  }))
}
