import { Activity } from '@/types'

export const dummyActivities: Activity[] = [
  {
    name: 'Purchase',
    icon: 'https://picsum.photos/200',
    iconBg: '#e0f7fa',
    type: 'debit',
    amountColor: '#FF0000',
    from: 'Shop A',
    neroGas: '0.1',
    amount: '-50.1',
  },
  {
    name: 'Salary',
    icon: 'https://picsum.photos/200',
    iconBg: '#fff3e0',
    type: 'credit',
    amountColor: '#0000FF',
    from: 'Company B',
    neroGas: '0.0',
    amount: '+1000',
  },
  {
    name: 'Gift',
    icon: 'https://picsum.photos/200',
    iconBg: '#e8f5e9',
    type: 'credit',
    amountColor: '#0000FF',
    from: 'Friend C',
    neroGas: '0.0',
    amount: '+200',
  },
  {
    name: 'Bill Payment',
    icon: 'https://picsum.photos/200',
    iconBg: '#fce4ec',
    type: 'debit',
    amountColor: '#FF0000',
    from: 'Utility D',
    neroGas: '0.2',
    amount: '-100.2',
  },
  {
    name: 'Transfer',
    icon: 'https://picsum.photos/200',
    iconBg: '#f3e5f5',
    type: 'debit',
    amountColor: '#FF0000',
    from: 'Bank E',
    neroGas: '0.3',
    amount: '-300.3',
  },
]
